### ISSUE TITLE
你好我发现一个bug

### ISSUE THREAD

**Issue by lobster002** [yjfnypeu/Router#4]
在Utils 类里边 isHttp(String scheme)方法 
public  boolean isHttp(String scheme) {
        return scheme.equalsIgnoreCase("http") || scheme.equalsIgnoreCase("https");
    }

就是这个  当有时候 获取的uri不是很规范  比如没有scheme是  或者比如 www.baidu.com这样写，而不是http：//www.baidu.com时 ，会直接crash掉

所以建议写成这样：

public  boolean isHttp(String scheme) {
       return "http".equalsIgnoreCase(scheme) || "https".equalsIgnoreCase(scheme);
  }

**Comment by yjfnypeu** [comment]
多谢建议，不过建议尽量不要出现这种没有scheme的情况，因为写的时候我是默认所有的都是应该有scheme的。毕竟这应该是一种基本规范。下个版本会考虑对空scheme的情况做点兼容。对无scheme的情况下默认添加使用scheme。可以解决此类问题。

**Comment by yjfnypeu** [comment]
@lobster002 你的问题已经解决。更新0.5版本就可以了
