### ISSUE TITLE
网页APP内部跳转

### ISSUE THREAD

**Issue by Thewhitelight** [yjfnypeu/Router#5]
![image](https://cloud.githubusercontent.com/assets/7720611/21977761/8b1cccf0-dc12-11e6-9127-617df023af91.png)

你好 我想web页面APP内部跳转，是否可以支持下  互换这两个是否可以

**Comment by yjfnypeu** [comment]
嗯。可以的。不会影响功能。因为之前没遇到这种需求。所以没有考虑。明天我改改发个版本吧。多谢支持

**Comment by yjfnypeu** [comment]
已发版1.1版本。你换这个版本试试吧

**Comment by Thewhitelight** [comment]
非常感谢 @yjfnypeu

**Comment by Thewhitelight** [comment]
在自己的WebActivity中 怎样才能拿到url呢
![image](https://cloud.githubusercontent.com/assets/7720611/22005623/d1014d08-dc9f-11e6-9b61-6bd1c5052cf3.png)
是否可以通过这个加入Uri 然后再WebActvity中getData拿到后load

**Comment by yjfnypeu** [comment]
哦。这个是拿不到的。我还以为你是要把不同的http的映射到不同的native页面。这种你可以针对原有的url进行一下封装。比如给你的WebActivity的链接设置为web://activity，要访问的url是http://www.baidu.com.就做层包裹。使用web://activity?url=http://www.baidu.com.这样把数据传递过去。这也是普遍做法了吧
