### ISSUE TITLE
parseParams方法对于value为什么要decode

### ISSUE THREAD

**Issue by Thewhitelight** [yjfnypeu/Router#9]
这个类下![image](https://user-images.githubusercontent.com/7720611/53079976-97078480-3532-11e9-8925-8ebac0dd7dc3.png)
![image](https://user-images.githubusercontent.com/7720611/53080009-aab2eb00-3532-11e9-9c5b-365d0613cd72.png)
你好 请问这里为什么要decode 不太理解

**Comment by Thewhitelight** [comment]
刚在看了下代码 原来在上面有encode 我用的老版本没有encode

**Comment by Thewhitelight** [comment]
我用demo 传入url `haoge://page/user-info?username={"url":"https://jmttest.oss-cn-hangzhou.aliyuncs.com/AABca%2BT1HlTfpJfa.png"}` 但是在目标页面拿到 %2B 为 + 号了

**Comment by yjfnypeu** [comment]
@Thewhitelight 对于这种参数中本身有特殊字符的。最好是进行参数拼接的时候先将参数进行一次encode。

**Comment by Thewhitelight** [comment]
谢谢 我现在也是这么做的,但是对于服务器返回的字段不能确定里面是否有特殊字符,所以一些页面需要encode,感觉有点麻烦.
